#!/bin/bash

cd "$(dirname "$0")"

dest="$1"
if [ "$dest" == "" ]; then
	echo "Usage: ./upload <destination>"
	echo "Example: ./upload mysite.com:some/path"
	exit 1
fi

options="--stats -azPe ssh --exclude=.DS_Store"

rsync index.html favicon.ico "${dest}/" $options
rsync ../../Assets "${dest}/" $options
rsync ../../Server "${dest}/" $options
