clean:
	rm -rf Projects/android/obj
	rm -rf Projects/android/bin
	rm -rf Projects/android/gen
	rm -rf Projects/android/assets
	rm -rf Projects/android/libs/armeabi
	rm -rf Projects/android/libs/armeabi-v7a
	rm -rf Projects/android/libs/x86
	rm -rf Projects/android/libs/mips
