#!/bin/bash

cd "$(dirname "$0")"

dest="$1"
if [ "$dest" == "" ]; then
	echo "Usage: ./upload <destination>"
	echo "Example: ./upload mysite.com:some/path"
	exit 1
fi

options="--stats -azPe ssh --exclude=.DS_Store"

rsync proj.html5/* "${dest}/" $options
rsync proj.html5 "${dest}/" $options
rsync js "${dest}/" $options
rsync res "${dest}/" $options
rsync server "${dest}/" $options
